---
title: "Part 1: A very imperfect example"
author: 
  - "Lars Vilhuber"
  - "Marie Connolly"
date: "`r Sys.Date()`"
output: 
  ioslides_presentation:
  incremental: false
self-included: true
widescreen: true
---
  
```{r, child=c('toc.md')}
```

## Overview

::: {.columns-2}

:::: {.column}

- A Github package with a paper, code, data

::::
  
:::: {.column}

- **Goal**: Let's reproduce! 

::::
  
:::

# A very imperfect example

## A Github page {.smaller}

```{r github1,echo=FALSE}

knitr::include_url("https://github.com/labordynamicsinstitute/very-imperfect-example")

```

## The "paper"

```{r readmeweb2,echo=FALSE}

knitr::include_url("https://github.com/labordynamicsinstitute/very-imperfect-example/blob/main/text/main.pdf")

```


## Your turn

- Download the "very imperfect example"
- Reproduce Table 1
- You have 10 minutes

## Top chrono

```{=html}
<p id="demo" style="text-align: center;font-size: 60px;margin-top: 0px;"></p>

<script>
// Set the date we're counting down to - units are 1/1000 s
var start = new Date().getTime() + (10 * 60 * 1000);

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = start - now;

  // Time calculations for days, hours, minutes and seconds
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Display the result in the element with id="demo"
  document.getElementById("demo").innerHTML =  minutes + "m " + seconds + "s ";

  // If the count down is finished, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "FINISHED";
  }
}, 1000);
</script>
```

## Next


```{r, child=c('toc.md')}
```
